# src/buildpolaris_ai/platform/schemas.py
"""
Strict Pydantic schemas defining the contract between buildpolaris_bff and buildpolaris_ai.
These mirror the ERPNext/Frappe DocTypes defined in the platform spec (Section 9.1).
"""
from datetime import datetime
from enum import Enum
from typing import Any, Literal, Optional
from pydantic import BaseModel, Field

# Note: In production, we will use uuid7, but standard uuid4 is fine for local dev setup
from uuid import uuid4 

class CDCEventType(str, Enum):
    CREATED = "created"
    UPDATED = "updated"
    DELETED = "deleted"

class CDCEvent(BaseModel):
    """
    Payload published by buildpolaris_bff's cdc_publisher.py.
    Consumed by buildpolaris_ai's graph_sync_worker.py.
    """
    event_id: str = Field(default_factory=lambda: str(uuid4()))
    event_type: CDCEventType
    doctype: str  # e.g., "RFI", "DailyLog", "Task"
    docname: str  # The ERPNext document name/ID
    tenant_id: str
    project_id: str
    timestamp: datetime
    payload: dict[str, Any] # The actual document data

class GateStatus(str, Enum):
    PENDING = "Pending"
    APPROVED = "Approved"
    REJECTED = "Rejected"

class ActionApprovalGate(BaseModel):
    """
    The payload buildpolaris_ai sends to buildpolaris_bff's agent_writes.py 
    to request a guarded write action (FR-8.4, NFR-AI-6).
    """
    gate_id: Optional[str] = None # Generated by BFF if creating a new gate
    ref_doctype: str
    ref_docname: Optional[str] = None
    initiator_type: Literal["system"] = "system"
    proposed_payload: dict[str, Any]
    status: GateStatus = GateStatus.PENDING
    model_version: str
    confidence_score: float = Field(ge=0.0, le=1.0)
    tool_trace_id: str = Field(default_factory=lambda: str(uuid4()))

class UserContext(BaseModel):
    """
    Passed from PWA -> BFF -> AI Sidecar to enforce row-level data isolation (FR-1.5).
    The AI layer NEVER broadens this scope.
    """
    user_id: str
    tenant_id: str
    company_id: str
    assigned_project_ids: list[str]
    role: str